### ISSUE TITLE
bioproject linking to DDBJ, which doesn't work.

### ISSUE THREAD

**Issue by TrisSN** [identifiers-org/identifiers-org.github.io#107]
For bioproject id: PRJNA635377
identifiers.org provides this link: https://identifiers.org/bioproject:PRJNA635377
However, this links to the DDBJ version, and it doesn't resolve.

I know the solution to this is to add /ncbi/ before bioproject, as I noticed the same issue before. However, I think it's important this is rectified on your end, as you're currently recommending links that don't work.

**Comment by mbdebian** [comment]
Thanks for bringing this to our attention, we'll review this issue as soon as possible.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Dear @TrisSN ,
I have reviewed this issue, and it seems to be an _ID space coverage issue_
I'm afraid that, as long as alternative providers that don't cover the full ID space in the namespace where they are registered. Taking into account that identifiers.org has no information on ID space coverage for the resources in the registry, it is not possible for the resolver to know if a particular LUI (Locally Unique Identifier) corresponds to a dataset that has been deposited in a given provider, as a way around this, we offer _provider codes_ mechanism, for telling the resolver that you'd like the resolution to be locked to a particular provider.
Checking this in real time when resolving a compact identifier has been proven to be very complex due to the spread misused of HTTP Status codes in the replies by resources, as well as the widespread use of Javascript for populating the content of landing pages, which makes rendering them very expensive.
In addition, identifiers.org only holds information on how to check the validity of a LUI in the context of a namespace, thus, having no information on how much of the ID space is currently being used.
For 'bioproject', not having a provider flagged as 'primary', and all of the registered ones having the same ranking, a random one is chosen.
I hope you find this information useful @TrisSN , please, don't hesitate to get back to us in case you need anything else.
Kind Regards,
Manuel
