### ISSUE TITLE
More `pgx` changes

### ISSUE THREAD

**Issue by mbaudis** [identifiers-org/identifiers-org.github.io#129]
Apologies for another change request, but we're revamping our resource ...

So for Progenetix `pgx`:

#### Description

    The Progenetix database provides an overview of mutation data in cancer, with a focus on copy number abnormalities (CNV / CNA), for all types of human malignancies. The resource contains genome profiles of more than 130'000 individual samples and represents about 700 cancer types, according to the NCIt "neoplasm" classification. Additionally to this genome profiles and associated metadata, the website present information about thousands of publications referring to cancer genome profiling experiments, and services for mapping cancer classifications and accessing supplementary data through its APIs.

#### Local pattern

We want to be able to provide information about other identifiers, e.g. in the _obo_ style (`obo:__prefix___underscore___id___`), e.g. `pgx:geo_GSE22328`; therefore now:

`'^\w{3,15}[-_]\w[\w.-]{3,128}$`

**Comment by mbdebian** [comment]
Hi @mbaudis ,

Thanks for submitting the request for changes to [pgx](https://registry.identifiers.org/registry/pgx) namespace.

Would it be possible to have a description for the namespace itself, e.g.?
```
The Progenetix database provides an overview of mutation data in cancer, with a focus on copy number abnormalities (CNV / CNA), for all types of human malignancies. The resource contains genome profiles of more than 130'000 individual samples and represents about 700 cancer types, according to the NCIt "neoplasm" classification. Additionally to this genome profiles and associated metadata, information about thousands of publications referring to cancer genome profiling experiments is offered.
```

And an additional text to describe the provider itself? This second description would be the best fit for mentioning the data mapping services API.

Thanks in advance @mbaudis .

I'm looking forward for your feedback on this, in order to move your request forward.

Kind regards,
Manuel

**Comment by mbdebian** [comment]
Hi @mbaudis ,

I just wanted to let you know that I have just updated the information in the registry.

Kind regards,
Manuel

**Comment by mbaudis** [comment]
@mbdebian Apologies for not adding more - but the change works nicely. Thanks!
