### ISSUE TITLE
Update ITO URL pattern

### ISSUE THREAD

**Issue by matthias-samwald** [identifiers-org/identifiers-org.github.io#169]
Please update the ITO (https://registry.identifiers.org/registry/ito#!) URL pattern from

https://bioportal.bioontology.org/ontologies/ITO/?p=classes&conceptid=https%3A%2F%2Fai-strategies.org%2Fontology%2F{$id}

to

https://bioportal.bioontology.org/ontologies/ITO/?p=classes&conceptid=https%3A%2F%2Fidentifiers.org%2Fito%3A{?id}

Thanks!

**Comment by renatocjn** [comment]
Change made. Please email changes to identifiers-org@ebi.ac.uk on future changes. We wish to keep GitHub issues for development discussion.

**Comment by cthoyt** [comment]
@renatocjn I'm following all changes on this repo and I think it's a big mistake to ask people to use email instead of the GitHub issue tracker. This has several pitfalls that Identifiers.org much less transparent:

- it makes it less possible for the community to engage in discussion
- it makes it more likely for duplicate issues, wasting the valuable time of the Identifiers.org team
- it makes it harder/impossible to assess how responsive the Identifiers.org team is
- if the resource is ever deprecated, it means there will not be a public record of changes/discussion

If you have team members who are less comfortable using GitHub, it's always possible to have github forward notifications to an internal email inbox

**Comment by renatocjn** [comment]
@cthoyt thank you for your interest in all the activity :)

First, to address the responsiveness of the team, due to recent changes in EBI, a lot of the personnel dedicated to identifiers.org had to be moved to other projects. But a few months ago I got allocated to handle all the issues, so expect things to be handled to the best of my abilities.

To be honest with you, I was quite surprised with the content with the issues in the repository. I was informed with I joined the team that I should be taking care of curation requests through the e-mail and EBI's request tracker. Which is why I'm instructing everyone to use the e-mail. 

I agree that the GitHub issue tracker has a much better interface and accessibility. I can discuss the change of support venue in our next meeting. The only worry I have with GitHub issues is that it would be difficult to track given the number of repositories that the project has.

Regarding community engagement, for general discussion and usage help, these GitHub issues are great since they allow anyone to contribute. But for entry updates, this is not really necessary since this is only with namespace maintainers.

We are hoping to implement tombstone entries soon to address deprecated or dead resources. These will include information such as the reason for it and relevant dates. We will base our implementations on eosc's PID documents.

Anyway, these are just my opinions, I will be discussing this with Henning in our next meeting soon.

Best regards.

**Comment by cmungall** [comment]
I strongly endorse the proposal to keep everything transparent on GitHub, this has worked incredibly well for bioregistry.io. This is particularly important for identifier prefixes, where there are many stakeholders for a lot of prefixes, including the authorities themselves.

**Comment by matthias-samwald** [comment]
I also think that the transparency of GitHub issues is preferable to an e-mail based system.
(And I'm humbled that my issue from ages ago triggered this important discussion 😅 )

**Comment by cthoyt** [comment]
> First, to address the responsiveness of the team, due to recent changes in EBI, a lot of the personnel dedicated to identifiers.org had to be moved to other projects. But a few months ago I got allocated to handle all the issues, so expect things to be handled to the best of my abilities.

This is wonderful news! I hope this also means that you will be able to act as a community liaison and help improve the transparency of Identifiers.org.

I would welcome you to join the [OBO Foundry Community Slack workspace](https://join.slack.com/t/obo-communitygroup/shared_invite/zt-1lfe3ubv5-pw_QlK2abiWo4yVl6n1mMg) where a large community uses the `#prefixes` channel to discuss prefixes, CURIEs, and URIs at the interface with other informatics efforts in the life and natural sciences.

> To be honest with you, I was quite surprised with the content with the issues in the repository. I was informed with I joined the team that I should be taking care of curation requests through the e-mail and EBI's request tracker. Which is why I'm instructing everyone to use the e-mail.

If you get the chance to talk to more stakeholders, I think they will echo the same as me, Chris, and Matthias. The Slack I linked would be a great place to start asking around (e.g., with a poll).

> I agree that the GitHub issue tracker has a much better interface and accessibility. I can discuss the change of support venue in our next meeting.

In the Bioregistry project, we created a new prefix request form using GitHub issues form templates. You can see this looks very nice and has a good amount of error checking built in. See the form [here](https://github.com/biopragmatics/bioregistry/issues/new?assignees=biopragmatics%2Fbioregistry-reviewers&labels=New%2CPrefix&template=new-prefix.yml&title=Add+prefix+%5BX%5D) and the configuration that generates the form [here](https://github.com/biopragmatics/bioregistry/blob/main/.github/ISSUE_TEMPLATE/new-prefix.yml).

> The only worry I have with GitHub issues is that it would be difficult to track given the number of repositories that the project has.

It's for sure not ideal how many repositories there are for Identifiers.org, but most of them are scary front-end code and people tend to find their way here. Improving the READMEs, documentation, and issue templates for all of these repositories could mitigate that issue.

> Regarding community engagement, for general discussion and usage help, these GitHub issues are great since they allow anyone to contribute. But for entry updates, this is not really necessary since this is only with namespace maintainers.

Based on the number of issues where people requested fixes to existing namespaces for which they are not maintainers, I would disagree that it's not necessary, especially if Identifiers.org doesn't have adequate staff dedicated to curation.

> Anyway, these are just my opinions, I will be discussing this with Henning in our next meeting soon.

It would be great if we schedule a one-on-one chat, since we're working in a similar space. I'll be returning to Europe next week and generally am free before 15.00 CEST. As I mentioned in passing above, I'm working on the Bioregistry project, which pulls from Identifiers.org and several other registries, aligns information, fills in gaps, and provides tooling for end users. You might be interested to read about this project in the mean time:

- https://github.com/biopragmatics/bioregistry
- https://bioregistry.io
- https://www.nature.com/articles/s41597-022-01807-3

**Comment by renatocjn** [comment]
That is great @cthoyt, I will join slack soon and I would be happy to provide any information on idorg that the community requires.

We currently have registration request forms on our website and I doubt we will be changing that anytime soon given the current queue of development. Updating the documentation is one of these tasks that I should be tackling soon.

It would be great to talk more with you about bioregistry :)
