### ISSUE TITLE
LUI pattern for PANTHER Pathway Component (panther.pthcmp) is invalid

### ISSUE THREAD

**Issue by piotr-gawron** [identifiers-org/identifiers-org.github.io#186]
Current pattern does not match the Sample ID.

I think that `^G\|P\|U\|C\|S\d{5}$` should be changed to `^[GPUCS]\d{5}$`

**Comment by dhimmel** [comment]
Also noting a previous report of this in https://github.com/identifiers-org/identifiers-org.github.io/issues/99#issuecomment-627006826.

This issue was fixed in Bioregistry in https://github.com/biopragmatics/bioregistry/issues/242, which you might be a better fit for your application.

**Comment by piotr-gawron** [comment]
Dear @dhimmel,

I'm not looking for regex to match identifier. I was trying to  resolve Panther identifier to the database entry. But due to the fact that regex is invalid, identifiers.org is not resolving even sample identifier - try to click on Sample URL on this page: https://registry.identifiers.org/registry/panther.pthcmp.

The same happens if I try to resolve valid identifier using Resolve a Compact Identifier tool: https://identifiers.org/resolve?query=panther.pthcmp:P00266

**Comment by cthoyt** [comment]
This might be a solution for you @piotr-gawron - you can use this URL to properly resolve to the right page https://bioregistry.io/panther.pthcmp:P00266

**Comment by renatocjn** [comment]
@piotr-gawron Thanks for catching the error. I made the change on the namespace, hopefully, it works fine now. We are hoping to improve our automated curation tool to catch this type of error automatically in the future.

Also, in the future, please send this type of communication through our email identifiers-org@ebi.ac.uk since we are hoping to keep the GitHub issues for development discussions.
