### ISSUE TITLE
How does content negotiation work?

### ISSUE THREAD

**Issue by rpgoldman** [identifiers-org/identifiers-org.github.io#191]
The identifiers.org web site states that "responses encoded in RDF/XML are provided via content negotiation, other formats are being added."

Does your content negotiation support the standard behavior with human readable pages coming when HTML is requested, and others when requested?

And with respect to machine readable formats, is only RDF/XML supported, or can we link to other notations (Turtle, and Manchester Syntax would be nice for our purposes).

Thank you

**Comment by renatocjn** [comment]
Hello, the documentation was actually not correct. We recently updated it to be closer to the current services.

At the moment, identifiers.org only exports data through JSON.  Sorry for the delay to answer since it took me a while to make sure of this. If you wish to acquire metadata through identifiers.org, you should have a look at our [metadata API](https://docs.identifiers.org/pages/metadata_service.html), here is an example: <http://metadata.api.identifiers.org/reactome:R-HSA-446203>
