### ISSUE TITLE
Id pattern needs to be modified for PMR

### ISSUE THREAD

**Issue by jonrkarr** [identifiers-org/identifiers-org.github.io#194]
Also sent to curator@identifiers.org in December 2021.

PMR has two schemes for identifiers for simulation projects (basically, they have an older style and a newer style). The older scheme is currently registered with the `pmr` prefix. The newer scheme is not currently registered. I think this is best handled by revising the `pmr` record as outlined below. (I suggest lumping the two styles in to one record because PMR presents these as one namespace to users. Alternatively, a separate record could be created for the newer style. Please follow whatever makes most sense for Identifiers.org.)

- Local Unique Identifier (LUI) pattern: ^(exposure\/[a-z0-9]{32,32}|e\/\d+)$
- URL pattern: [https://models.physiomeproject.org/{$id}](https://models.physiomeproject.org/%7B$id%7D)
- Sample ids: 
  - exposure/ebf69ca24298b28b2361e7d43eb52d6c
  - e/412
- Sample compact identifiers
  - pmr:exposure/ebf69ca24298b28b2361e7d43eb52d6c
  - pmr:e/412
- Sample URLs
  - https://identifiers.org/pmr:exposure/ebf69ca24298b28b2361e7d43eb52d6c
  - https://identifiers.org/pmr:e/412

**Comment by renatocjn** [comment]
Hello,
From what I can see in the registry, we currently have pmr and pmr.workplace registered. Where the current pmr resolves to the exposure type of IDs that you describe. 

Could you tell me if there are semantic differences between the data artifacts being identified?
I assume there are which makes me think that we should create two new namespaces (ex: pmr.exposure and pmr.e) in order to allow these to have independent metadata descriptions. The current pmr would be kept in order to maintain existing IDs working.

If you think this is not the case, then I can try to register as you described but I'm not sure that the current resolver will allow for the "/" in the LUI as you described. I will have to test it.

I wait on what you think is best.

**Comment by renatocjn** [comment]
@jonrkarr, any comments on this?
