### ISSUE TITLE
Updates to OMIM Namespace Data

### ISSUE THREAD

**Issue by fschiettecatte** [identifiers-org/identifiers-org.github.io#204]
Hi, I am the lead developer for the OMIM website and would like to have some of the information updated, it is not clear from the website how one would go about doing this.

**Comment by cthoyt** [comment]
hi @fschiettecatte, it's the case that the Identifiers.org team hasn't been able to respond to issues for the last few years. There's a new project called the Bioregistry that does something similar but has a much more community-focused governance and curation model. You can see the OMIM page on https://bioregistry.io/registry/omim, and let us know what would be the most appropriate updates via our issue tracker https://github.com/biopragmatics/bioregistry/issues/new/choose

**Comment by renatocjn** [comment]
Hello @fschiettecatte,
Could you describe the changes that you wish to be made? 

We currently do not allow users to directly update their entries since we wish for our curator team to validate them beforehand.

**Comment by fschiettecatte** [comment]
Hi @renatocjn

I am not asking for access at all, and there is extensive discussion in https://github.com/biopragmatics/bioregistry/issues/497 as to what we are asking for.

Thanks!

**Comment by renatocjn** [comment]
Hello,

From what I saw in the discussion, we would need to change the LUI pattern of the OMIM namespace of identifiers.org but the URL pattern seems to still work. The current patterns use the "/entry" component. Do you wish to remove the component from our URL pattern as it seems resolution also works without it?

You also ask in the discussion to add alternative names to the namespace in order to resolve OMIM, omim, mim and MIM prefixes. It seems that you changed your mind during the discussion and you just need the "mim" prefix to work. is that current? Just FYI, identifers.org does not support alternative prefixes to namespaces with its current implementation but it is case-insensitive.

Have I missed anything?
