### ISSUE TITLE
NCBI Taxonomy update at identifiers.org

### ISSUE THREAD

**Issue by cls44** [identifiers-org/identifiers-org.github.io#218]
I am the product owner for NCBI Taxonomy and I am interested in improving our own recommendations for the formatting of Taxonomy IDs. 
We are currently recommending an unspecific prefix followed by text and numbers, for example, referring to Homo sapiens: 
NCBI:txid9606
identifiers.org resolves with another generic prefix;
taxonomy:9606

I am still considering the best way to improve our recommended format, but it may also involve a registry update at identifiers.org. How could we proceed?

**Comment by cls44** [comment]
Ok, makes sense. Not clear then what, if anything, should change at identifiers.org if we adapt our own formatting recommendations to something like "ncbi.txid:9606" ? Regardless, I will send an update email when it happens.

**Comment by renatocjn** [comment]
Great, I wait for your contact then.

**Comment by cthoyt** [comment]
> Ok, makes sense. Not clear then what, if anything, should change at identifiers.org if we adapt our own formatting recommendations to something like "ncbi.txid:9606" ? Regardless, I will send an update email when it happens.



> Ok, makes sense. Not clear then what, if anything, should change at identifiers.org if we adapt our own formatting recommendations to something like "ncbi.txid:9606" ? Regardless, I will send an update email when it happens.

@cls44 this would be an incredible improvement for the biomedical community for NCBI to adopt more standard CURIEs, however, I would suggest doing `ncbi.taxon` or directly `ncbitaxon` since this is how everyone is already referring to NCBI Taxonomy entries in most ontology and FAIR data settings.

Can you additionally identify yourself? What is your name so we can cross-reference that you're the NCBI Taxonomy data owner?
