### ISSUE TITLE
MAMO terms no longer resolved

### ISSUE THREAD

**Issue by ntung** [identifiers-org/identifiers-org.github.io#234]
Hi Renato,

[MAMO](https://registry.identifiers.org/registry/mamo) terms are no longer resolved. It seems OLS4 has removed it. Can you double-check it? As you are aware, BioModels heavily replies on MAMO. We hope the issue will be fixed soon. Thanks!

**Comment by ntung** [comment]
I have also created a request [EBIPSPOT:OLS4:592](https://github.com/EBISPOT/ols4/issues/592).

**Comment by renatocjn** [comment]
Hi, I will have a look, You may want to look into this for the moment:
https://github.com/EBISPOT/ols4/issues/388

**Comment by renatocjn** [comment]
From what I see, mamo is not available at all anymore in OLS4 and OLS3 is no longer available because they added a redirection. It seems that this is also a problem with [BioPortal](https://bioportal.bioontology.org/ontologies/MAMO) because it won't open it's classes and properties.

I will open a ticket with bioportal and wait on the OLS4 solution. The namespace is completely unresolvable for the moment.

**Comment by renatocjn** [comment]
Closing this since the issue was solved by the OLS4 team
