### ISSUE TITLE
OMIA update

### ISSUE THREAD

**Issue by ImkeTammen** [identifiers-org/identifiers-org.github.io#242]
I am the curator of OMIA - MIR:00000142 and noted that we haven’t updated you regarding some changes to this resource.
1.	The URL has changed from http://omia.angis.org.au/ to https://www.omia.org/ and the URL pattern and Home URL need to be changed accordingly in your registry.
2.	The Institution has been changed from ‘Reprogen, Faculty of Veterinary Science, University of Sydney’ to ‘Sydney School of Veterinary Science, Faculty of Science, The University of Sydney’
3.	The link to the Institution ROR is https://ror.org/0384j8v12 - I am not sure how this translates into a ROR ID
4.	It appears that the information in N2T is equally out of date and I was advised that requesting these changes here will automatically update information in N2T. Is that correct?
5.	I noted that the sample ID for OMIA is given as ‘1000’ – however OMIA uses the following IDs – either OMIA:xxxxxx or  OMIA:xxxxxx-yyyy.., where xxxxxx is the 6-digit number for a trait/disorder, and yyyy.. is the NCBI species taxonomy id (usually four digits, but sometimes longer). Should the sample ID in the registry be changed accordingly? Is that something we request here or in bioregistry? 
Example URL links are 
https://www.omia.org/OMIA001000/ for OMIA:001000
https://www.omia.org/OMIA001000/9615/ for OMIA:001000-9615
6.	We have also introduced recently a new ID OMIAvariantID:x, where x is a consecutive number starting from 1 and at the moment going up to 1578. These IDs are currently not linked to a public facing URL (URL is only visible to database curators). Can the OMIAvariantID:x be registered with identifiers.org or should this be done via the bioregistry?

**Comment by renatocjn** [comment]
Dear @ImkeTammen, thank you for keeping us up to date on this.

1. I updated the home URL and URL pattern.
2. I can add another resource for the new institution and deprecate the existing resource. That is how we usually do so that there is historical information of past institutional involvement. Is that ok for you?
3. I can't put a ROR ID of the University of Sydney when you register the resource under the School of Veterinary. The new resource I create would be without a ROR ID. I hope this isn't a problem.
4. Theoretically yes, I'm not sure how up-to-date N2T is. It has been a while since we got news from them.
5. The local namespace ID in our case is whatever is past the colon and the part before the colon is the prefix, hence why the sample ID is just '1000'. There wouldn't be any problem creating an ID pattern for both OMIA types but identifiers.org resolution is a direct pattern replacement, it is not able to rewrite the URL pattern by taking parts of the ID like it is required for the OMIAs with the NCBI species. Would it be possible for you to add an endpoint on your side to redirect to the correct page when requested to go http://www.omia.org/OMIA001000-915 or something like that? Similar to what you do when <http://www.omia.org/OMIA1000> is requested.
6. We would be happy to have the OMIAVariantID prefix registered on identifiers.org, you just have to make a prefix request [here](https://registry.identifiers.org/prefixregistrationrequest). I'm happy to assist if you need any help with the form. It will just have to be verified by our curators, and for that, it will have to be publicly accessible.

**Comment by renatocjn** [comment]
For point 2, it should be fine since it's the same institution. Right now it has "Reprogen, Faculty of Veterinary Science, University of Sydney". Is Reprogen not important here then? Or should it be "Reprogen, Sydney School of Veterinary Science, Faculty of Science, The University of Sydney" ?

For point 3, this is more of a pattern that we use in identifiers.org. We only use the ROR ID if only the institution of the ROR ID is associated with the resource. In this case, the University of Sydney. We don't use ROR IDs when resources are associated with subgroups (like schools or faculties) under the ROR ID institution because this can mess with how identifiers.org identifies institutions internally. The same is done when multiple institutions are associated with a resource. It could be something we change in the future, but for now, that's how it's done.

**Comment by renatocjn** [comment]
Done, thank you for helping keep us up to date.
