### ISSUE TITLE
Mismatch between LUI pattern and URL pattern for MGI

### ISSUE THREAD

**Issue by jgtate** [identifiers-org/identifiers-org.github.io#243]
There seems to be a mismatch between the LUI pattern for MGI (`^MGI:\d+$`) and the URL patterns (e.g. `http://www.informatics.jax.org/accession/MGI:{$id}`) for the Mouse Genome Database resources. 

The LUI definition includes the prefix in the regex, and "Prefix embedded in LUI" is set to "yes", suggesting that IDs should contain the prefix, e.g. `MGI:1858201`. We're therefore storing the ID with the prefix attached but when we insert that into the URL pattern it causes a duplication of the prefix: `http://www.informatics.jax.org/accession/MGI:MGI:1858201`.

I think the URL patterns for the three MGD resources need to be updated to remove the prefix.

**Comment by renatocjn** [comment]
Unfortunately, the "Prefix embedded in LUI" flag is quite confusing. Which is why we try not to use it when possible. It is mostly only used for validation. Internally, the rewritter still splits the id and the prefix.

Is the prefix duplication happening to you? It doesn't seem to be the case for these two examples:
- http://identifiers.org/MGI:2442292
- http://identifiers.org/MGI:1858201

**Comment by jgtate** [comment]
Ah. We're not trying to use the API to resolve the identifier like that. Instead, the ID that we store in our database has the prefix attached, e.g. `MGI:2442292`, like in your example, because that seems to be what's suggested by the entry in identifiers.org. In our code we retrieve the URL pattern from identifiers.org, i.e. `http://www.informatics.jax.org/accession/MGI:{$id}`, and insert the ID, which means the final URL includes the duplicate prefix.

**Comment by renatocjn** [comment]
I see the issue. Unfortunately, it is how it is implemented and we are not able to put the time to work on this now. You will have to handle this on your side. I can leave this thread open to see how many would be interested in changing this behaviour. I remember this was brought up before.

**Comment by jgtate** [comment]
I understand. I'm not sure we need a change in behaviour though, just an update to the URL patterns for the MGD resource. For example, changing `http://www.informatics.jax.org/accession/MGI:{$id}` to `http://www.informatics.jax.org/accession/{$id}` would resolve our issue. Is that a possibility?

**Comment by renatocjn** [comment]
Then the resolved URL would be invalid. For example, http://identifiers.org/MGI:1858201 would resolve to http://www.informatics.jax.org/accession/1858201.

**Comment by jgtate** [comment]
OK, so the ID is taken as `2442292`, rather than `MGI:2442292`. Thanks for clarifying. We'll go back to our code and database and resolve this at our end. 

I'll mark this issue as closed but just to point out that it still feels like there's an inconsistency for MGI between the values of `Local Unique Identifier (LUI) pattern` (given in [the registry](https://registry.identifiers.org/registry/mgi) as `^MGI:\d+$`) and `Sample ID (LUI)` (`2442292`). Shouldn't the MGI entry at least behave like that for [HGNC](https://registry.identifiers.org/registry/hgnc), where the prefix is shown as not embedded in the LUI and is optional in the regex?

Thanks for your help.

**Comment by renatocjn** [comment]
Just to be a bit more clear, only the numerical ID is taken when rewriting the URL to redirect the user. The prefix embedded in LUI only affects when verifying the request against the LUI pattern. This is likely to correct rewrite URLs for some namespaces. Although, I quickly looked but couldn't find an example for you.

You are right, it's a weird inconsistency with HGNC.I would say I can't have both working in the same way since the prefix is optional for HGNC. 

What we should probably do HGNC is remove the prefix from the regex since it accepts URIs like http://identifiers.org/hgnc:hgnc:2674 but I don't know if the intention was to allow things like http://identifiers.org/hgnc:HGNC:2674; which is weird in of itself.
