### ISSUE TITLE
Link to namespace no longer works

### ISSUE THREAD

**Issue by jonovik** [identifiers-org/identifiers-org.github.io#64]
It is a great strength of identifiers.org that one can not only look up an identifier, but also what _kind_ of identifier it is. So https://identifiers.org/ncbigene used to explain exactly what kind of "gene identifier" this is, where the data collection resides, what the identifiers look like (syntactic format), etc. Now the link just says `INVALID Compact Identifier resolution request for 'ncbigene'`.

I really would like to have the old functionality back.

**Comment by javfg** [comment]
Hi Jon,

The functionality you are looking for is still there. There are different ways you can get to it:

- The new url to access the details about ncbigene (or any other namespace) is [https://registry.identifiers.org/registry/ncbigene](https://registry.identifiers.org/registry/ncbigene). It is a longer address because you are now accessing the registry browser.

- From the resolution services web ([http://identifiers.org](http://identifiers.org)), you can navigate to the details about a namespace by clicking on the link icon in the suggestion list:

![Peek 2019-06-25 11-24](https://user-images.githubusercontent.com/6058151/60091140-d2fa6280-973b-11e9-8111-48903d5ee640.gif)

- Another way you can reach that page is by using the registry browser, as detailed in [the docs](https://docs.identifiers.org/articles/services.html#registryservices).

In any case, I added an [entry to the migration page](https://docs.identifiers.org/articles/migration.html#registry) so any other users can find the related info.

Thank you very much for the feedback! It is greatly appreciated.

**Comment by jonovik** [comment]
Thank you for this explanation, for the pointers to the new arrangements,
and for your work on this valuable resource. If I may argue my case a bit
further:

- This change is breaking existing URLs. This is exactly what I was hoping
identifiers.org would help me avoid.
- The new solutions are hard to remember. It's been so easy to teach my
colleagues that "if you wonder what this data collection is properly
called, just remove the last part of the URL".

**Comment by mbdebian** [comment]
Thanks a lot for your feedback @jonovik.
We've made a major rebuilding of identifiers.org with this cycle, in fact, the whole platform is new, there is nothing from the old platform there, except for the data in the registry.
New releases, specially those of the magnitude of this one, come with some changes that sometimes involved an adaptation process on the way the platform was used. This changes are most of the time for the good, e.g. improved and more robust resolution services, better performance, the possibility of multi-cloud and on-premises deployments, a lot more functionality, better and more comprehensive data models, etc.
We understand that changes may cause discomfort and some inconveniences for the community in general, and the developers in particular.
In this case, the new identifiers.org is actually three new platforms: resolution and metadata services, the central registry, and the documentation around all this.
When using https://identifiers.org, the platform that replies back is the specialised on resolution services, i.e. on our compact identifier URLs and associated resources. While https://registry.identifiers.org is specialised in the central registry, which is all about browsing, searching, curating and working, in general, with the central registry.
This way, we can deliver our resolution services, specially for programmatic access, in a more robust and efficient way is the best fit for them (commercial cloud, hybrid cloud setup or on premises).
That's the reason why https://identifiers.org doesn't serve details on namespaces, but, in any case, let me have a look at this use case in the context of the new cloud native platform.
Thanks again for your feedback, we're constantly looking for information on how our community uses our services.

**Comment by mbdebian** [comment]
Hi @jonovik ,
I'm glad to let you know that we have developed this mechanism of accessing a namespace by just removing the ':....? part of the compact identifier, as per your request.
It is now live on our production site.
Thanks again for reaching out and providing us with valuable feedback.
