### ISSUE TITLE
New prefixes submitted notification

### ISSUE THREAD

**Issue by afilisetti** [identifiers-org/identifiers-org.github.io#67]
Hi, 
I have recently submitted the form for two prefixes (dlxb and dlxc). I have not received any notification about the submissions. Are the submissions under evaluation? or something went wrong? 

cheers, 

Alessandro

**Comment by mbdebian** [comment]
Hi @afilisetti ,
Thanks a lot for reaching out.
It’s been a month since we released the new platform, and, with every release, there are some rough edges that need to be polished, some bug fixing and optimisation actions... etc.
We’re working on the notification subsystem, on both the technical and GDPR side of things, so we’ll hopefully have that up and running soon.
Regarding your submissions, if you saw the “Submitted” green check on the UI, that means it went through, but I’ll have a look at the API later to double check it worked.
Thanks again for reaching out @afilisetti , we really appreciate the feedback from our users.

**Comment by afilisetti** [comment]
thanks @mbdebian for the quick response. It's always a pleasure to be helpful. Ok, thus I assume our submissions are "under evaluation". 
Thank's again, 

Alessandro
