### ISSUE TITLE
registry not available

### ISSUE THREAD

**Issue by micheldumontier** [identifiers-org/identifiers-org.github.io#76]
https://registry.identifiers.org/registry

**Comment by mbdebian** [comment]
Thanks for reporting this @micheldumontier , this is due to a problem with a managed data backend that is not correctly performing its failover mechanism.
The issue is being investigated in the cloud environment and we hope it will be resolved as soon as possible.
Please, don't hesitate to contact us in case you've got any other query.
Thanks,
Manuel
