### ISSUE TITLE
URL pattern for retrieving identifier info based on MIR number

### ISSUE THREAD

**Issue by allysonlister** [identifiers-org/identifiers-org.github.io#79]
Good afternoon all,

I have a couple of questions (that may be very simple, and I'm just missing something obvious!) relating to the registry. Looking at https://registry.identifiers.org/registry/spp, I see that the legacy MIR number is MIR:00000726 and the current one is MIR:00000730, but searching the registry at https://registry.identifiers.org/ for either of these identifiers returns 0 results for either these MIR values or the search terms "spp" or "signaling". Why can't I find this entry in the registry? Browsing the registry correctly shows SPP where you'd expect in the S section, but that's the only way I can get to it.

Equally, I'm fairly sure that I used to be able to build a URL to an identifiers.org record as follows:

```
https://www.ebi.ac.uk/miriam/main/datatypes/ + identifier 
```

(e.g. https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000730)

But I think that the URL has changed now. Please could you let me know the correct way to automatically build a link to a record using the MIR identifier?

Thanks very much!
Allyson

**Comment by mbdebian** [comment]
Hi @allysonlister ,
I'd like to thank you for reaching out with this query.
Over the past few years, identifiers.org has undergone a separation process from MIRIAM, becoming an independent entity, that was consolidated back in June when we released the new cloud native identifiers.org platform.
The old platform will still be available until the end of the year, but it's not receiving updates since June.
The new platform focuses on identifiers.org main mission, which is about resolution services for compact identifiers.
Because of that joint past with MIRIAM, identifiers.org registry holds information on MIR IDs for namespaces and providers (previously known as data collections and resources), but they're not officially supported. Yet, for legacy purposes, we do mint new MIR IDs when new namespaces or resources are registered in identifiers.org, and we're bug fixing a resolution mechanism for people to be able to, given a MIR ID, use it as a compact identifier in the resolver and get redirected to the correct entry in the registry.
When browsing the registry, you'll see "Legacy registry identifier" under the namespace general information section, also, you'll see a MIR ID associated with every provider in the namespace. Both of them are there for legacy purposes, and they're supposed to be understood by MIRIAM for all the registry entries prior to June 2019, but, as you pointed out for 'spp', this namespace and its main provider has just been registered in identifiers.org, and there is no synchronisation mechanism in place for MIRIAM to get updates from identifiers.org, nor for identifiers.org to get updates from MIRIAM (in case it is ever updated).
I hope you've found this information useful, and I'd like to thank you for your patience while we fix the MIR resolution mechanism.
Please, don't hesitate to get back in touch in case you've got any other questions.
Best,
Manuel
