### ISSUE TITLE
Misleading error message when searching for record without a domain

### ISSUE THREAD

**Issue by peterwharrison** [identifiers-org/identifiers-org.github.io#83]
If you search for "PRJEB402" you get the error message "Your compact identifier appears to be incorrect: The prefix prjeb402  does not exist in the registry."

If you search for "ena.embl:PRJEB402" you find the valid identifier.

Therefore you should either allow search without domain so that it would be found (suggesting multiple options if it exists in multiple domains), or change your error message to detect that as you haven't included a colon then you "need to supply a valid domain to search for identifiers". Telling the user that a record doesn't exist when the real error is that they haven't supplied a domain is misleading.

**Comment by mbdebian** [comment]
Dear @peterwharrison ,
I'd like to thank you for your feedback on this, and to extend my apologies for the delay in getting back to you, somehow, this feedback ended up lost in our kanban board.
PRJEB402 is not a compact identifier, and the search functionality is built for searching compact identifiers, as it is stated above the text box.
I think it would be interesting to see if we could offer a full registry regex match list of options as the user types in random text in the search box, in an efficient and informative way, that doesn't negatively impact the experience of the user on the interface.
Another easier approach could be along the lines of what you mention, i.e. tell the user, as he/she is typing, that whatever is being typed is not a compact identifier until it hits the first ':', but I think this approach would be redundant, because the search box is designed for interactivity, so the user can see, in real time, the different prefixes that partially or completely match the current content of the search box.
Thanks again for your feedback, we'll take into account to see how it evolves around community usage of identifiers.org services.
Kind Regards,
Manuel
