### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Midnighter** [identifiers-org/identifiers-org.github.io#85]
Hi, I have two possibly related problems/questions.

1. When I access the entire registry dataset via the API (as described here https://docs.identifiers.org/articles/api.html#getdataset), the response has a key `"apiVersion": null`. This should probably be set to `'v1'`.
2. I am using Identifiers.org in a large set of chemical and reaction identifiers. I would like to include information on which state/version of Identifiers.org this data set is built. Of course, I can include the time of access to the API but is there some other versioning scheme that would allow me to see if data has changed?

Thank you in advance.

**Comment by mbdebian** [comment]
Hi @Midnighter , nice catch! thanks a lot for reporting this.
'apiVersion' was the initial mechanism we put in place for API versioning, but it has nothing to do with the contents of the registry.
The fact that is 'null' on that response, it means it's a minor bug we need to fix, its value should be '1.0'
Identifiers.org registry is not versioned, because it refers to current namespaces and live resources, when a resource changes and / or disappears, its previous information has no value, specially the URL patterns, as they would not work.
I hope this answers your questions.
Thanks again for reaching out to us, and please, don't hesitate to do so if you had any more questions.
Best Regards,
Manuel
