### ISSUE TITLE
ena.embl:SRC000025 does not resolve via http://identifiers.org/ena.embl:SRC000025

### ISSUE THREAD

**Issue by ianfore** [identifiers-org/identifiers-org.github.io#90]
Step 1: If I ask identifiers.org to resolve the compact id ena.embl:SRC000025 by entering it on the page at http://identifiers.org it resolves correctly.

Step 2: If I try and resolve the same compact ID via the URL http://identifiers.org/ena.embl:SRC000025 it does not resolve.

That URL is given in response to step 1 is exactly the one I am using in step 2.

**Comment by mbdebian** [comment]
Hi @ianfore ,

Thanks a lot for reaching out, I have tried this example and it doesn't seem to be a problem with the resolver.

If you try to search for 'SRC000025' at [ENA](https://www.ebi.ac.uk/ena), you get the same result (see picture below).
<img width="1792" alt="Captura de pantalla 2020-03-31 a las 10 25 07" src="https://user-images.githubusercontent.com/8855107/78010118-e75a3400-7339-11ea-9f18-8eb1ba163a9c.png">

It is my understanding that many resources at the EBI are undergoing some intense maintenance, that may be affecting their normal operation.

But I think this offers me a good chance to highlight that the resolution process is a multi-step process:

1. A metaresolver is contacted with a compact identifier, e.g. [ena.embl:SRC000025](http://identifiers.org/ena.embl:SRC000025)
2. The metaresolver computes (resolves) the final URL, in this case from [ENA](https://www.ebi.ac.uk/ena/data/view/SRC000025)
3. Because URL resolution mechanism has been used, an HTTP 302 response is sent back to the caller, with this information
4. The requesting client follows the redirection response

Up to step 3, the metaresolver has done its job, the error page that shows up now, when the user visits the Resolved [URL](https://www.ebi.ac.uk/ena/data/view/SRC000025), may be due to a couple of reasons:
1. The registry information regarding ENA as a provider in identifiers.org is out of date.
2. The provider is having some trouble delivering their services

I think '2' is more likely to be what's happening, as I know that many resources at the EBI are undergoing intense maintenance.

@ianfore, I hope you find this information useful

Please, don't hesitate to let me know if you need anything else.

Best Regards,
Manuel
