### ISSUE TITLE
URIs creator

### ISSUE THREAD

**Issue by maximeDelmas** [identifiers-org/identifiers-org.github.io#93]
Dear Administrator,

I would like to work with the system you have developed to create Identifiers.org URIs. 
For a set of resources for which I have the namespace (e.g. chebi) and a set of identifiers (e.g. 17790) I would like to generate the set of possible URIs from those you have provided as resources such as https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:{$id}"  and also the URI Identifiers.org respecting the namespace and the associated pattern (e.g. ^CHEBI:\d+$) to create for example http://identifiers.org/chebi/CHEBI:17790.

Is there a tool or a WebService that could build this set of URIs?

Thanks for your help,

Best regards,

Maxime D.

**Comment by mbdebian** [comment]
Dear @maximeDelmas ,

Thanks a lot for your request.

We currently offer no particular endpoint for building compact identifiers and / or identifiers.org URLs based on the combination of namespace and LUI (Locally Unique Identifier).

An identifiers.org URL would be https://identifiers.org/<prefix>:<accession>

You can access information on any namespace via our REST API at https://registry.api.identifiers.org (please, see [documentation](https://docs.identifiers.org/articles/api.html#namespaces))

Please, pay special attention to the attribute 'namespaceEmbeddedInLui', when 'true', like in the case of 'CHEBI', instead of using the value of the attribute 'prefix', you would need to use the beginning of the regular expression that defines the ID Space, e.g. in CHEBI the regular expression is '^CHEBI:\d+$', the prefix is the string between '^' and ':'.

Attribute 'namespaceEmbeddedInLui' is a compact identifier beautifying mechanism that was born with ontologies, which were already using an appearance like compact identifiers, and they didn't like their compact identifier appearance, e.g. for CHEBI it would have been 'chebi:CHEBI:17790'.
This attribute tells the resolution services that the namespace is allowed to use 'naked' LUIs (accessions) instead of the full compact identifier.
And because the LUI (accession) is being used, and detected, at the resolution services, it must match the ID space verification regular expression, e.g. a CHEBI LUI is 'CHEBI:17790' but not '17790'.

I hope you find this information useful, and I'd like to add that we take note of this use case, that could be useful for the community.

Please, don't hesitate to contact us in case you need anything else.

Kind Regards,
Manuel
