### ISSUE TITLE
Should redirect to https

### ISSUE THREAD

**Issue by agarny** [identifiers-org/identifiers-org.github.io#94]
If you ask your browser to load `identifiers.org` then it the URL in the browser will effectively be `http://identifiers.org/` while I would expect it to be `https://identifiers.org/`, i.e. use `https` rather than `http`.

**Comment by mbdebian** [comment]
Dear @agarny ,
Thanks for your support request.
When it comes to URLs, it is common practice that you just type in the browser the domain name, and it will autocomplete with 'http://' by default.
Nowadays, where most of the internet has moved to HTTPS, it is a common practice that, when hitting a web server with HTTP, our browser gets an HTTP 301 Permanently Moved response with the same URL, but HTTPS as protocol.
In the case of identifiers.org, although it all looks like a single system, we are, in fact, running two different services:
- Resolution Services, available via HTTP and HTTPS at identifiers.org. There are several reasons behind this setup:
  1. Some legacy pipelines from the community, working with our resolution services, for some reason, don't use / can't use HTTP. This is also why we don't issue HTTP 301 responses back to clients reaching our services via HTTP.
  2. Everything (data and functionality) around our resolution services is open, and un-authenticated, so there's no real need to encrypt anything.
  3. This also saves our users from browser blocking their custom Javascript clients deployed locally, as the browser would not be a big fun of mixing HTTP and HTTPS
- Registry, at https://registry.identifiers.org, this is available via HTTPS only, and we don't redirect clients from HTTP to HTTPS due to technical setup limitations between Kubernetes GLB Ingress controller and GCP GLB, not exposing all the properties of the GLB.
I hope you find this information useful, @agarny , please, don't hesitate to get back in touch in case you need anything else.
Kind Regards,
Manuel
