### ISSUE TITLE
Error for Human Disease Ontology prefix

### ISSUE THREAD

**Issue by ariutta** [identifiers-org/identifiers-org.github.io#96]
The prefix for https://registry.identifiers.org/registry/doid is currently `DOID\`. I think it should be just `DOID` without the backslash.

The sample url doesn't resolve:
https://identifiers.org/DOID\:11337
But that url with the backslash removed does resolve:
https://identifiers.org/DOID:11337

**Comment by mbdebian** [comment]
Thanks for reporting this @ariutta , we'll have a look at it as soon as possible.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Please, have a look at my reply to this [issue](https://github.com/identifiers-org/identifiers-org.github.io/issues/100) on this.
Thanks,
Manuel

**Comment by mbdebian** [comment]
Another comment on this, the extra '\' is an encoding artifact for the string describing the regular expression with escape characters that we are looking at unifying between frameworks, libraries and encoding standards, but the regex is correct, as it validates 'DOID:11337' as belonging to that namespace.
Thanks again @ariutta for reporting this.
Kind Regards,
Manuel

**Comment by dhimmel** [comment]
So the issue is that currently on https://registry.identifiers.org/registry/doid the "Prefix" and "Sample Compact identifier" fields include an extraneous `\`?

![image](https://user-images.githubusercontent.com/1117703/79471647-ddd6fa00-7fd0-11ea-8e36-2f7567c40334.png)

Seems like the root cause of the issue could be trying to reverse engineer the actual prefix from the regex pattern when `namespaceEmbeddedInLui` is true rather than storing it as its own field in the database?

**Comment by dhimmel** [comment]
The backslash issue also affects https://registry.identifiers.org/registry/gramene.growthstage:

![image](https://user-images.githubusercontent.com/1117703/79473423-1b3c8700-7fd3-11ea-8de7-9d76c51132e3.png)
